after-startup-command = [
  'exec-and-forget borders',
  'exec-and-forget sketchybar'
]
exec-on-workspace-change = [
	'/bin/bash',
	'-c',
	'/opt/homebrew/opt/sketchybar/bin/sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE',
]

start-at-login = true

[gaps]
inner.horizontal = 10
inner.vertical =   10
outer.left =       12
outer.bottom =     10
outer.top =        46
outer.right =      12

[[on-window-detected]]
  if.app-id = 'org.mozilla.firefox'
  run = 'move-node-to-workspace 1'

[[on-window-detected]]
  if.app-id = 'com.mitchellh.ghostty'
  run = 'move-node-to-workspace 2'

[[on-window-detected]]
  if.app-id = 'app.legcord.Legcord'
  run = 'move-node-to-workspace 3'

[[on-window-detected]]
  if.app-id = 'com.spotify.client'
  run = 'move-node-to-workspace 4'

[mode.main.binding]

# All possible keys:
# - Letters.        a, b, c, ..., z
# - Numbers.        0, 1, 2, ..., 9
# - Keypad numbers. keypad0, keypad1, keypad2, ..., keypad9
# - F-keys.         f1, f2, ..., f20
# - Special keys.   minus, equal, period, comma, slash, backslash, quote, semicolon, backtick,
#                   leftSquareBracket, rightSquareBracket, space, enter, esc, backspace, tab
# - Keypad special. keypadClear, keypadDecimalMark, keypadDivide, keypadEnter, keypadEqual,
#                   keypadMinus, keypadMultiply, keypadPlus
# - Arrows.         left, down, up, right

# All possible modifiers: cmd, alt, ctrl, shift
alt-cmd-ctrl-e = 'join-with right'
alt-cmd-ctrl-v = 'join-with up'

# alt-cmd-ctrl-e = 'layout tiles horizontal vertical'

alt-cmd-ctrl-j = 'focus left'
alt-cmd-ctrl-k = 'focus down'
alt-cmd-ctrl-l = 'focus up'
alt-cmd-ctrl-semicolon = 'focus right'

alt-cmd-ctrl-shift-j = 'move left'
alt-cmd-ctrl-shift-k = 'move down'
alt-cmd-ctrl-shift-l = 'move up'
alt-cmd-ctrl-shift-semicolon = 'move right'

alt-cmd-ctrl-shift-minus = 'resize smart -50'
alt-cmd-ctrl-shift-equal = 'resize smart +50'

alt-cmd-ctrl-1 = 'workspace 1'
alt-cmd-ctrl-2 = 'workspace 2'
alt-cmd-ctrl-3 = 'workspace 3'
alt-cmd-ctrl-4 = 'workspace 4'
alt-cmd-ctrl-5 = 'workspace 5'

alt-cmd-ctrl-shift-1 = 'move-node-to-workspace 1'
alt-cmd-ctrl-shift-2 = 'move-node-to-workspace 2'
alt-cmd-ctrl-shift-3 = 'move-node-to-workspace 3'
alt-cmd-ctrl-shift-4 = 'move-node-to-workspace 4'
alt-cmd-ctrl-shift-5 = 'move-node-to-workspace 5'

alt-cmd-ctrl-tab = 'workspace-back-and-forth'
alt-cmd-ctrl-shift-tab = 'move-workspace-to-monitor --wrap-around next'

alt-cmd-ctrl-shift-r = 'reload-config'
alt-cmd-ctrl-r = 'mode resize'

[mode.resize.binding]
j = 'resize width -50'
k = 'resize height +50'
l = 'resize height -50'
semicolon = 'resize width +50'
enter = 'mode main'
esc = 'mode main'
